### ISSUE TITLE
Faster natural breaks

### ISSUE THREAD

**Issue by abyrd** [conveyal/gridualizer#22]
We're currently using Jenks breaks which is an O(n^2) algorithm. This article suggests a new method using Ckmeans:
https://medium.com/@dschnr/using-clustering-to-create-a-new-d3-js-color-scale-dec4ccd639d2#.jbp4kf7vg

Using this module:
https://www.npmjs.com/package/d3-scale-cluster

**Comment by mattwigway** [comment]
We can also make Jenks breaks tractable at all times by taking a sample of the data values. This is what the quantile classifier does, using a seed based on the data itself so the breaks are stable.

**Comment by abyrd** [comment]
I think the 1970s Jenks algorithm is completely superseded by the much faster CkMeans, which apparently produces better clusters as well.

**Comment by abyrd** [comment]
I just replaced Jenks with ckmeans in my branch, commit 18d08c0898b81608a2597f1781768e5aff27176c. It's still fairly slow, so I've used the sampling approach with it too.
